### ISSUE TITLE
Successful environment 

### ISSUE THREAD

**Issue by hoon-ock** [txie-93/cdvae#63]
This works for me. 

```
name: cdvae
channels:
  - pytorch 
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.2.89
  - pip
  - numpy=1.24.4
  - pandas=2.0.3
  - matplotlib-base=3.7.3
  - seaborn=0.13.2
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - pytorch-lightning=1.3.8
  - ruamel.yaml=0.16.6
  - matminer=0.7.3
  - pip:
      - -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
      - torch==1.9.0
      - torch-scatter==2.0.7
      - torch-sparse==0.6.10
      - torch-cluster==1.5.9
      - torch-spline-conv==1.2.1
      - torch_geometric==2.5.3
      - higher==0.2.1
      - hydra-core==1.1.0
      - hydra-joblib-launcher==1.1.5
      - p-tqdm==1.3.3
      - pymatgen==2023.8.10
      - pytest==8.2.1
      - python-dotenv==1.0.1
      - smact==2.2.1
      - streamlit==0.79.0
      - torchmetrics==0.5.0
      - wandb==0.10.33
```

**Comment by GurjotDhaliwal** [comment]
AttributeError: module 'distutils' has no attribute 'version'

**Comment by mit-lbrey** [comment]
@GurjotDhaliwal 
> AttributeError: module 'distutils' has no attribute 'version'

Try to downgrade `setuptools==59.5.0`

**Comment by mit-lbrey** [comment]
This works for me with an RTX A5000
```yaml
name: cdvae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pip
  - numpy=1.24.4
  - pandas=2.0.3
  - matplotlib-base=3.7.3
  - seaborn=0.13.2
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - pytorch-lightning=1.3.8
  - ruamel.yaml=0.16.6
  - matminer=0.7.3
  - pip:
      - -f https://data.pyg.org/whl/torch-1.9.0%2Bcu111.html
      - torch==1.9.0
      - torch-scatter==2.0.7
      - torch-sparse==0.6.10
      - torch-cluster==1.5.9
      - torch-spline-conv==1.2.1
      - torch_geometric==2.5.3
      - higher==0.2.1
      - hydra-core==1.1.0
      - hydra-joblib-launcher==1.1.5
      - p-tqdm==1.3.3
      - pymatgen==2023.8.10
      - pytest==8.2.1
      - python-dotenv==1.0.1
      - smact==2.2.1
      - streamlit==0.79.0
      - torchmetrics==0.5.0
      - wandb==0.10.33
```
then 
```bash
pip install setuptools==59.5.0
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

export LD_LIBRARY_PATH="<path_to_your_miniconda_env>/lib:$LD_LIBRARY_PATH"
```
